version: '3'
services:
  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - app-network
  node-app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
