version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    networks:
      - app-db
  backend:
    build: ./
    container_name: api_c
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-db
volumes:
  mongodb:
networks:
  app-db:
